CREATE TABLE [CTL].[CTL_WATERMARK] (

	[WATERMARK_ID] int NOT NULL, 
	[INTEGRATION_ID] int NULL, 
	[INTEGRATION_SESSION_NAME] varchar(100) NULL, 
	[LAST_WATERMARK_VALUE] datetime2(6) NULL, 
	[CURRENT_WATERMARK_VALUE] datetime2(6) NULL, 
	[STATUS] varchar(20) NULL, 
	[CREATED_DT] datetime2(6) NULL, 
	[UPDATED_DT] datetime2(6) NULL
);